apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-eta-deployment
  labels:
    app: server-eta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-eta
  template:
    metadata:
      labels:
        app: server-eta
    spec:
      containers:
      - name: server-eta
        image: server-eta:0.0.4
        ports:
        - containerPort: 80