apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: busservice-ingress
spec:
  rules:
    - host: busservice.info
      http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: server-eta-service
                port:
                  number: 8080
          - path: /etasign
            pathType: Prefix
            backend:
              service:
                name: client-etasign-service
                port:
                  number: 8080

